module: SBValidator
author: Soumen Bhuin
github_url: https://github.com/smbhuin/SBValidator

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, SBValidator.xcodeproj, -target, SBValidator iOS, LIBRARY_SEARCH_PATHS=.build/debug]
